export { default as PButton } from './button/Button.vue'
export { default as PImage } from './image/Image.vue'
export { default as PCountdown } from './countdown/Countdown.vue'
export { default as PModal } from './modal/Modal.vue'
export { default as PRank } from './rank/Rank.vue'
export { default as PBarrage } from './barrage/Barrage.vue'
